### ISSUE TITLE
Errors occurred while registering commands.

### ISSUE THREAD

**Issue by jacklollz2** [rspatial/terra#947]
cloud.commandframework.bukkit.BukkitCommandManager$BrigadierFailureException: Could not initialize Brigadier mappings. Reason: paper brigadier initialization failure (null)
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:134) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:68) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1115) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[purpur-1.19.3.jar:git-Purpur-1862]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        ... 10 more
Caused by: java.lang.IllegalStateException: Could not find Registry Registry field
        at cloud.commandframework.bukkit.internal.RegistryReflection.lambda$static$2(RegistryReflection.java:71) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
        at cloud.commandframework.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:71) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:109) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.<init>(MinecraftArgumentTypes.java:103) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.internal.MinecraftArgumentTypes.<clinit>(MinecraftArgumentTypes.java:78) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.registerMappings(BukkitBrigadierMapper.java:82) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.bukkit.BukkitBrigadierMapper.<init>(BukkitBrigadierMapper.java:75) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.paper.PaperBrigadierListener.<init>(PaperBrigadierListener.java:57) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        at cloud.commandframework.paper.PaperCommandManager.registerBrigadier(PaperCommandManager.java:128) ~[Terra-bukkit-6.2.1-BETA+358e09d05-shaded.jar:?]
        ... 10 more
[17:27:45 INFO]: [Terra] Disabling Terra v6.2.1-BETA+358e09d05

**Comment by jacklollz2** [comment]
Wrong github.
